name: hacksteak
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02
  dio: ^5.3.2

  http: ^0.13.3
  intl: ^0.17.0

  openapi_generator_annotations: ^4.11.0
  #  page_transition: ^2.0.9
  #  simple_animations: ^5.0.2
  animations: ^2.0.7
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  flutter_screenutil: ^5.8.4
  responsive_framework: ^1.1.0
  #  palette_generator: ^0.3.3+2
  flex_color_scheme: ^7.2.0
  #  flex_color_picker: ^3.3.0
  bloc: ^8.1.2
  analyzer: ^6.0.0
  enhanced_future_builder: ^2.0.0
  timeago: ^3.3.0
  #  font_awesome_flutter: ^10.5.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  #  extended_nested_scroll_view: ^6.1.2
  #  pixel_snap: ^0.1.2
  #  space_fixer: ^0.1.1
  #  web_smooth_scroll: ^1.1.0
  #  flutter_improved_scrolling: ^0.0.3
  #  dyn_mouse_scroll: ^1.0.7
  go_router: ^11.1.2
  webview_flutter: ^4.4.1
  matcher: ^0.12.16
#  flutter_html: ^3.0.0-beta.2
  html_unescape: ^2.0.0
  url_launcher: ^6.1.14
  linkify: ^5.0.0
  universal_html: ^2.2.4
#  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  openapi_generator: ^4.11.1
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
    - family: RobotoFlex
      fonts:
        - asset: fonts/RobotoFlex-Regular.ttf
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf
    - family: RobotoMono
      fonts:
          - asset: fonts/RobotoMono-Regular.ttf

scripts:
  gen: dart run build_runner build --delete-conflicting-outputs
